// resources/js/Pages/Admin/Products/Create.vue
<script setup>
import { ref } from 'vue'
import { router, usePage } from '@inertiajs/vue3'
import AdminLayout from '../../../Layouts/AdminLayout.vue'

const props = defineProps({
  attributeFamilies: { type: Array, default: () => [] },
})

const page = usePage()
const errors = ref({})
const loading = ref(false)

const form = ref({
  name: '',
  attribute_family_id: '',
  type: 'simple',
  sku: '',
})

const submit = () => {
  loading.value = true
  errors.value = {}

  router.post('/admin/products', form.value, {
    onFinish: () => {
      loading.value = false
    },
    onError: (validationErrors) => {
      errors.value = validationErrors
      loading.value = false
    },
  })
}

const cancel = () => {
  router.visit('/admin/products')
}
</script>

<template>
  <AdminLayout>
    <div class="max-w-lg mx-auto">
      <div class="rounded-xl border border-gray-200 dark:border-slate-800 bg-white dark:bg-slate-900/50 shadow-xl overflow-hidden">
        <div class="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-slate-800">
          <div>
            <h1 class="text-lg font-semibold text-gray-900 dark:text-white">Create Product</h1>
            <p class="text-sm text-gray-500 dark:text-slate-400 mt-0.5">Add basic product information</p>
          </div>
          <button
            type="button"
            class="text-gray-400 dark:text-slate-400 hover:text-gray-900 dark:hover:text-white transition-colors"
            @click="cancel"
          >
            ✕
          </button>
        </div>

        <form class="p-6 space-y-5" @submit.prevent="submit">
          <div v-if="page.props.flash?.success" class="rounded-lg bg-emerald-500/10 border border-emerald-500/20 px-4 py-3 text-sm text-emerald-400">
            {{ page.props.flash.success }}
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2">
              Product Name <span class="text-red-400">*</span>
            </label>
            <input
              v-model="form.name"
              type="text"
              class="w-full px-4 py-2.5 rounded-lg bg-gray-50 dark:bg-slate-950/50 border text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
              :class="errors.name ? 'border-red-500' : 'border-gray-300 dark:border-slate-800'"
              placeholder="Enter product name"
            />
            <p v-if="errors.name" class="text-xs text-red-400 mt-1">{{ errors.name }}</p>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2">
              Product Type <span class="text-red-400">*</span>
            </label>
            <select
              v-model="form.type"
              class="w-full px-4 py-2.5 rounded-lg bg-gray-50 dark:bg-slate-950/50 border border-gray-300 dark:border-slate-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="simple">Simple</option>
              <option value="configurable">Configurable</option>
              <option value="virtual">Virtual</option>
              <option value="bundle">Bundle</option>
            </select>
            <p v-if="errors.type" class="text-xs text-red-400 mt-1">{{ errors.type }}</p>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2">
              Attribute Family <span class="text-red-400">*</span>
            </label>
            <select
              v-model="form.attribute_family_id"
              class="w-full px-4 py-2.5 rounded-lg bg-gray-50 dark:bg-slate-950/50 border text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
              :class="errors.attribute_family_id ? 'border-red-500' : 'border-gray-300 dark:border-slate-800'"
            >
              <option value="">Select Attribute Family</option>
              <option v-for="family in attributeFamilies" :key="family.id" :value="family.id">
                {{ family.name }}
              </option>
            </select>
            <p v-if="errors.attribute_family_id" class="text-xs text-red-400 mt-1">{{ errors.attribute_family_id }}</p>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2">
              SKU <span class="text-red-400">*</span>
            </label>
            <input
              v-model="form.sku"
              type="text"
              class="w-full px-4 py-2.5 rounded-lg bg-gray-50 dark:bg-slate-950/50 border text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500 uppercase"
              :class="errors.sku ? 'border-red-500' : 'border-gray-300 dark:border-slate-800'"
              placeholder="Enter SKU"
            />
            <p v-if="errors.sku" class="text-xs text-red-400 mt-1">{{ errors.sku }}</p>
          </div>

          <div class="flex items-center justify-end gap-3 pt-4 border-t border-gray-200 dark:border-slate-800">
            <button
              type="button"
              class="px-4 py-2 rounded-lg text-sm text-gray-500 dark:text-slate-400 border border-gray-300 dark:border-slate-700 hover:text-gray-900 dark:hover:text-white transition-colors"
              @click="cancel"
            >
              Cancel
            </button>
            <button
              type="submit"
              :disabled="loading"
              class="px-4 py-2 rounded-lg text-sm font-medium text-white bg-blue-600 hover:bg-blue-500 disabled:opacity-50 transition-colors"
            >
              {{ loading ? 'Saving...' : 'Save Product' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </AdminLayout>
</template>

// resources/js/Pages/Admin/Products/Create.jsx
import React, { useState, useEffect } from 'react';
import { router, usePage } from '@inertiajs/react';
import AdminLayout from '../../../Components/Admin/AdminLayout';
import ConfigurableAttributesModal from '../../../Components/Admin/ProductForms/ConfigurableAttributesModal';
import { X, Package, Save } from 'lucide-react';

export default function CreateProduct({ attributeFamilies }) {
  const { flash } = usePage().props;

  const [formData, setFormData] = useState({
    name: '',
    attribute_family_id: '',
    type: 'simple',
    sku: '',
  });
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);
  const [createdProduct, setCreatedProduct] = useState(null);
  const [showConfigurableModal, setShowConfigurableModal] = useState(false);

  // Show modal when flash.createdProduct arrives (after redirect from store())
  useEffect(() => {
    if (flash?.createdProduct && flash.createdProduct.type === 'configurable') {
      setCreatedProduct(flash.createdProduct);
      setShowConfigurableModal(true);
    }
  }, [flash?.createdProduct]);

  // Also show modal if set via onSuccess (fallback)
  useEffect(() => {
    if (createdProduct && createdProduct.type === 'configurable') {
      setShowConfigurableModal(true);
    }
  }, [createdProduct]);

  const handleSubmit = (e) => {
    e.preventDefault();
    setLoading(true);
    setErrors({});

    router.post('/admin/products', formData, {
      onFinish: () => setLoading(false),
      onSuccess: (page) => {
        const product = page.props.flash?.createdProduct || page.props.createdProduct;
        if (product) {
          setCreatedProduct(product);
          if (product.type !== 'configurable') {
            router.visit(`/admin/products/${product.id}/edit`);
          }
        }
      },
      onError: (errs) => {
        setErrors(errs);
        setLoading(false);
      },
    });
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value,
    }));
  };

  return (
    <AdminLayout>
      <div className="flex items-center justify-center min-h-screen" style={{ backgroundColor: '#111827' }}>
        <div className="w-full max-w-md rounded-xl shadow-2xl" style={{ backgroundColor: '#101827', borderColor: '#1E293B', borderWidth: '1px', borderRadius: '12px' }}>
          {/* Modal Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b" style={{ borderColor: '#1E293B' }}>
            <div className="flex items-center gap-3">
              <Package className="w-5 h-5" style={{ color: '#3B82F6' }} />
              <h2 className="text-lg font-bold" style={{ color: '#F8FAFC', fontSize: '18px', fontWeight: '600' }}>Create Product</h2>
            </div>
            <a
              href="/admin/products"
              className="p-1 rounded-lg transition hover:bg-white/10"
              style={{ color: '#94A3B8' }}
            >
              <X className="w-5 h-5" />
            </a>
          </div>

          {/* Modal Body */}
          <form onSubmit={handleSubmit} className="p-6 space-y-5">
            {/* Product Name */}
            <div>
              <label className="block text-sm font-medium mb-2" style={{ color: '#94A3B8' }}>
                Product Name <span className="text-red-400">*</span>
              </label>
              <input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleChange}
                placeholder="Enter product name"
                className="w-full px-4 py-2.5 rounded-lg text-sm focus:outline-none focus:ring-2 transition"
                style={{
                  backgroundColor: '#0C1524',
                  borderColor: errors.name ? '#EF4444' : '#1E293B',
                  color: '#F8FAFC',
                  borderWidth: '1px',
                }}
              />
              {errors.name && <p className="text-xs text-red-400 mt-1">{errors.name}</p>}
            </div>

            {/* Product Type */}
            <div>
              <label className="block text-sm font-medium mb-2" style={{ color: '#94A3B8' }}>
                Product Type <span className="text-red-400">*</span>
              </label>
              <select
                name="type"
                value={formData.type}
                onChange={handleChange}
                className="w-full px-4 py-2.5 rounded-lg text-sm focus:outline-none focus:ring-2 transition"
                style={{
                  backgroundColor: '#0C1524',
                  borderColor: errors.type ? '#EF4444' : '#1E293B',
                  color: '#F8FAFC',
                  borderWidth: '1px',
                }}
              >
                <option value="simple">Simple</option>
                <option value="configurable">Configurable</option>
                <option value="grouped">Grouped</option>
                <option value="bundle">Bundle</option>
                <option value="virtual">Virtual</option>
                <option value="downloadable">Downloadable</option>
              </select>
              {errors.type && <p className="text-xs text-red-400 mt-1">{errors.type}</p>}
            </div>

            {/* Attribute Family */}
            <div>
              <label className="block text-sm font-medium mb-2" style={{ color: '#94A3B8' }}>
                Attribute Family <span className="text-red-400">*</span>
              </label>
              <select
                name="attribute_family_id"
                value={formData.attribute_family_id}
                onChange={handleChange}
                className="w-full px-4 py-2.5 rounded-lg text-sm focus:outline-none focus:ring-2 transition"
                style={{
                  backgroundColor: '#0C1524',
                  borderColor: errors.attribute_family_id ? '#EF4444' : '#1E293B',
                  color: '#F8FAFC',
                  borderWidth: '1px',
                }}
              >
                <option value="">Select Attribute Family</option>
                {attributeFamilies.map((family) => (
                  <option key={family.id} value={family.id}>{family.name}</option>
                ))}
              </select>
              {errors.attribute_family_id && <p className="text-xs text-red-400 mt-1">{errors.attribute_family_id}</p>}
            </div>

            {/* SKU */}
            <div>
              <label className="block text-sm font-medium mb-2" style={{ color: '#94A3B8' }}>
                SKU <span className="text-red-400">*</span>
              </label>
              <input
                type="text"
                name="sku"
                value={formData.sku}
                onChange={handleChange}
                placeholder="Enter SKU"
                className="w-full px-4 py-2.5 rounded-lg text-sm focus:outline-none focus:ring-2 transition"
                style={{
                  backgroundColor: '#0C1524',
                  borderColor: errors.sku ? '#EF4444' : '#1E293B',
                  color: '#F8FAFC',
                  borderWidth: '1px',
                }}
              />
              {errors.sku && <p className="text-xs text-red-400 mt-1">{errors.sku}</p>}
            </div>

            {/* Modal Footer */}
            <div className="flex items-center justify-end gap-3 pt-4 border-t" style={{ borderColor: '#1E293B' }}>
              <a
                href="/admin/products"
                className="px-4 py-2 rounded-lg text-sm transition border"
                style={{
                  backgroundColor: 'transparent',
                  borderColor: '#1E293B',
                  color: '#94A3B8',
                }}
              >
                Cancel
              </a>
              <button
                type="submit"
                disabled={loading}
                className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm transition text-white disabled:opacity-50 disabled:cursor-not-allowed"
                style={{ backgroundColor: '#3B82F6', color: '#F8FAFC' }}
              >
                {loading ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    <span>Saving...</span>
                  </>
                ) : (
                  <>
                    <Save className="w-4 h-4" />
                    <span>Save Product</span>
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>

      {/* Configurable Attributes Modal */}
      {showConfigurableModal && createdProduct && (
        <ConfigurableAttributesModal
          product={createdProduct}
          attributeFamily={createdProduct.attributeFamily || null}
          onClose={() => {
            setShowConfigurableModal(false);
            router.visit(`/admin/products/${createdProduct.id}/edit`);
          }}
        />
      )}
    </AdminLayout>
  );
}
